server:
  port: 9001
  maxHttpHeaderSize: 10240000
spring:
  rabbitmq:
    #10.1.2.139
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtualHost: testhost
    publisherConfirms: true